version: "1.0"
services:
  emby:
    extends:
      file: emby.yml
      service: emby
  bazarr:
    extends:
      file: bazarr.yml
      service: bazarr
  radarr:
    extends:
      file: radarr.yml
      service: radarr
  qbittorrent:
    extends:
      file: qbittorrent.yml
      service: qbittorrent
  jackett:
    extends:
      file: jackett.yml
      service: jackett
  sonarr:
    extends:
      file: sonarr.yml
      service: sonarr
  lidarr:
    extends:
      file: lidarr.yml
      service: lidarr
  syncthing:
    extends:
      file: syncthing.yml
      service: syncthing
  pihole:
    extends:
      file: pihole.yml
      service: pihole
