version: "1.0"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true
    volumes:
      - $HOME/asrock-config/jackett/config:/config
      - $HOME/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
