version: "1.0"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=022
      - WEBUI_PORT=8084
    volumes:
      - /home/frablamo/asrock-config/qbittorrent/config:/config
      - /media/usb/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8084:8084
    restart: unless-stopped
